name: env_tutorial
on: [pull_request, push] # Triggers the workflow on when there is a push or pull request on the main branch

jobs:
  job1:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps:
      - name: step 1
        env:
          API_KEY: XXXXXXXXXXXX    # Environment variable
        run: echo "The API key is:${{env.API_KEY}}"   # reference your environment variables
      - name: step 2
        run: echo "The API key is:${{env.API_KEY}}"   # reference your environment variables