name: env_tutorial
on: [pull_request, push] # Triggers the workflow on when there is a push or pull request on the main branch

env:
  API_KEY: XXXXXXXXXXXX    # Environment variable

jobs:
  job1:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps:
      - name: name for job1
        run: echo "The API key is:${{env.API_KEY}}"   # reference your environment variables

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: name for job2
        run: echo "The API key is:$API_KEY"  # another way reference your environment variables