name: env_tutorial
on: [pull_request, push] # Triggers the workflow on when there is a push or pull request on the main branch

jobs:
  job1:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps:
      - name: step 1
        run: |
          echo "The job_id is:GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is:GITHUB_ACTION"   # reference the default environment variables
          echo "The file path of this action is:GITHUB_ACTION_PATH"  
          echo "The run id is:GITHUB_RUN_ID" 
          echo "The GitHub Actor's name is:GITHUB_ACTOR
      - name: step 2
        run: echo "The run id is:GITHUB_RUN_ID"  